2018-04-18 07:11:11,562 ERROR 5785 nodejs.ClusterClientNoResponseError: client no response in 13380963ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 5785
hostname: loveRain.local

2018-04-18 08:56:19,770 ERROR 5785 nodejs.ClusterClientNoResponseError: client no response in 3467183ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 5785
hostname: loveRain.local

2018-04-18 09:22:31,287 ERROR 5785 nodejs.ClusterClientNoResponseError: client no response in 1391370ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 5785
hostname: loveRain.local

2018-04-18 13:15:52,446 ERROR 5785 nodejs.ClusterClientNoResponseError: client no response in 10820366ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 5785
hostname: loveRain.local

2018-04-18 16:26:28,641 ERROR 5785 nodejs.ClusterClientNoResponseError: client no response in 11435905ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 5785
hostname: loveRain.local

2018-04-18 21:19:25,742 ERROR 20617 [-/192.168.10.158/-/45ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20617
hostname: loveRain.local

2018-04-18 21:19:27,367 ERROR 20617 [-/192.168.10.158/-/9ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20617
hostname: loveRain.local

2018-04-18 21:19:30,057 ERROR 20617 [-/192.168.10.158/-/10ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20617
hostname: loveRain.local

2018-04-18 21:19:30,694 ERROR 20617 [-/192.168.10.158/-/8ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20617
hostname: loveRain.local

2018-04-18 21:19:35,321 ERROR 20643 [-/192.168.10.158/-/46ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20643
hostname: loveRain.local

2018-04-18 21:19:43,219 ERROR 20643 [-/192.168.10.158/-/18ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20643
hostname: loveRain.local

2018-04-18 21:19:44,992 ERROR 20643 [-/192.168.10.158/-/10ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20643
hostname: loveRain.local

2018-04-18 21:19:45,795 ERROR 20643 [-/192.168.10.158/-/8ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20643
hostname: loveRain.local

2018-04-18 21:19:46,203 ERROR 20643 [-/192.168.10.158/-/8ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20643
hostname: loveRain.local

2018-04-18 21:19:46,332 ERROR 20643 [-/192.168.10.158/-/9ms POST /api] nodejs.TypeError: d.setd is not a function
    at ApiController.addOrder (/Users/chz/Desktop/credit/app/controller/api.js:304:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)

pid: 20643
hostname: loveRain.local

2018-04-19 02:47:11,406 ERROR 15778 nodejs.ClusterClientNoResponseError: client no response in 10817521ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 15778
hostname: loveRain.local

2018-04-19 14:37:59,356 ERROR 15778 nodejs.ClusterClientNoResponseError: client no response in 42627189ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 15778
hostname: loveRain.local

2018-04-19 15:03:10,784 ERROR 15778 nodejs.ClusterClientNoResponseError: client no response in 1142621ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/chz/Desktop/credit/node_modules/cluster-client/lib/leader.js:74:23)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)
name: 'ClusterClientNoResponseError'
pid: 15778
hostname: loveRain.local

